# Generated by Django 2.0.7 on 2022-12-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20221217_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
