# Generated by Django 3.2.5 on 2022-12-31 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20221231_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='内容')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('modify', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MyBlog.article', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
    ]
